Repository elastic/elasticsearch-ruby, pull requests merged in 2020-06, with the labels that each got.

#900 [DOCS] Reorganize README
  README.md
  docs/examples/README.md
Labels: documentation

#902 [DOCS] Adds License Header to APM example
  docs/examples/apm/elastic_sinatra_app.rb
  docs/examples/apm/pinger.rb
Labels: 7.x, 8.0, documentation

#913 [XPACK] Update generated code
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/async_search/submit.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/machine_learning/delete_data_frame_analytics.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/machine_learning/delete_expired_data.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/machine_learning/get_categories.rb
Labels: 8.0

#912 [X-PACK] Update generated code
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/machine_learning/delete_data_frame_analytics.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/machine_learning/get_categories.rb
Labels: 7.x

#915 Bulk docs
  elasticsearch-api/lib/elasticsearch/api/actions/bulk.rb
  elasticsearch-api/utils/thor/generator/endpoint_specifics.rb
  elasticsearch-api/utils/thor/templates/_documentation_top.erb
Labels: 8.0, backport

#921 [XPACK] Adds enrich endpoints
  elasticsearch-xpack/lib/elasticsearch/xpack.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/delete_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/execute_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/get_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/params_registry.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/put_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/stats.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/namespace/enrich.rb
Labels: 7.x, 8.0, backport

#925 [XPACK] Adds enrich endpoints
  elasticsearch-xpack/lib/elasticsearch/xpack.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/delete_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/execute_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/get_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/params_registry.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/put_policy.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/enrich/stats.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/namespace/enrich.rb
Labels: 7.9, 7.x

#926 [XPACK] Adds EQL endpoint
  elasticsearch-xpack/lib/elasticsearch/xpack.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/eql/params_registry.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/eql/search.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/namespace/eql.rb
Labels: 7.x, 8.0, backport

#927 [XPACK] Adds EQL endpoint
  elasticsearch-xpack/lib/elasticsearch/xpack.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/eql/params_registry.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/eql/search.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/namespace/eql.rb
Labels: 7.9, backport

#933 [API] Adds Rubocop file to Generator so end is aligned correctly
  elasticsearch-api/utils/thor/.rubocop.yml
  elasticsearch-api/utils/thor/generate_source.rb
Labels: 7.x, 8.0, backport

#934 [API] Adds Rubocop file to Generator so end is aligned correctly
  elasticsearch-api/utils/thor/.rubocop.yml
  elasticsearch-api/utils/thor/generate_source.rb
Labels: 7.9, 7.x, backport

#923 [DOCS] Update CHANGELOG and Release Notes for 7.8
  CHANGELOG.md
  docs/release_notes/78.asciidoc
  docs/release_notes/index.asciidoc
Labels: 8.0, documentation

#922 [DOCS] Update CHANGELOG and Release Notes for 7.8
  CHANGELOG.md
  docs/release_notes/78.asciidoc
  docs/release_notes/index.asciidoc
Labels: 7.x, documentation

#938 [API] Update field caps
  elasticsearch-api/lib/elasticsearch/api/actions/field_caps.rb
Labels: 7.x, 8.0, backport

#939 [API] Update field caps
  elasticsearch-api/lib/elasticsearch/api/actions/field_caps.rb
Labels: 7.9, 7.x, backport

#914 Transport/Connection: consider attributes values for equality
  elasticsearch-transport/lib/elasticsearch/transport/transport/connections/connection.rb
Labels: 7.9, 8.0

#944 Transport/Connection: consider attributes values for equality
  elasticsearch-transport/lib/elasticsearch/transport/transport/connections/connection.rb
Labels: 7.9, backport
