Repository elastic/elasticsearch-ruby, pull requests merged in 2020-11, with the labels that each got.

#1071 [DOCS] 7.10.0 Release notes
  CHANGELOG.md
  docs/release_notes/710.asciidoc
  docs/release_notes/index.asciidoc
Labels: 7.x, documentation

#1088 [Client] Fix extracting cloud host when cloud host provides a port
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/client_spec.rb
Labels: 7.x, backport, elasticsearch-transport

#1090 Test runner update 7x
  api-spec-testing/test_file.rb
Labels: 7.x, backport

#1073 [DOCS] Adds Connecting section to Ruby docs
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/overview.asciidoc
Labels: 7.x, 8.0, documentation

#1075 Updates make.sh
  .ci/Dockerfile
  .ci/make.sh
  Rakefile
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1094 [7.x][DOCS] Adds Connecting section to Ruby docs
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/overview.asciidoc
Labels: 7.x, documentation

#1095 [CI] Adds version qualifier to task to build release and snapshot
  .ci/make.sh
  .dockerignore
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1096 Extracts update version rake task
  Rakefile
  rake_tasks/update_version.rake
Labels: 7.x, CI

#1097 Extracts update version rake task
  Rakefile
  rake_tasks/update_version.rake
Labels: 7.x, backport

#1099 [CI] Use default value for version_qualifier in make.sh
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1101 [CI] Send default value (date) for version qualifier in make.sh
  .ci/make.sh
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1102 [CI] Make version instance variable in assemble task
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1093 [CI] Test Runner: Use better version comparision for skip_version
  api-spec-testing/test_file.rb
Labels: 7.x, backport, test-runner

#1091 [CI] Print out Elasticsearch container info
  rake_tasks/elasticsearch_tasks.rake
Labels: 7.x, CI, backport

#1106 [CI] Make output_dir parameterizable in make.sh
  .ci/make.sh
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1092 [CI] Test Runner: Use better version comparision for skip_version
  api-spec-testing/test_file.rb
Labels: 7.x, 8.0, test-runner

#1084 [Client] Fix extracting cloud host when cloud host provides a port
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/client_spec.rb
Labels: 7.10, 7.x, 8.0, elasticsearch-transport

#1107 [CI] Refactors make.sh
  .ci/make.sh
  rake_tasks/unified_release_tasks.rake
Labels: CI

#1108 [CI] Test Runner: Updates XPack templates in data cleanup
  api-spec-testing/test_file.rb
Labels: CI

#1112 [CI] Remove job for 7.9
  .ci/jobs/elastic+elasticsearch-ruby+7.9.yml
Labels: CI

#1111 [CI] Test runner: Refactors clear snapshots and repositories
  api-spec-testing/test_file.rb
  api-spec-testing/test_file/task_group.rb
Labels: CI

#1113 [XPACK] Top level methods defined in xpack client
  elasticsearch-xpack/lib/elasticsearch/xpack.rb
Labels: 7.x, backport, elasticsearch-api

#1115 Update version: master should be 8.0.0
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch-transport/lib/elasticsearch/transport/version.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/version.rb
  elasticsearch/elasticsearch.gemspec
  elasticsearch/lib/elasticsearch/version.rb
Labels: 8.0

#1116 Update version: 7.x should be next 7.x release
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch-transport/lib/elasticsearch/transport/version.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/version.rb
  elasticsearch/elasticsearch.gemspec
  elasticsearch/lib/elasticsearch/version.rb
Labels: 7.x

#1117 [CI] Makes version_qualifier parameter in make.sh
  .ci/make.sh
Labels: CI
