Repository elastic/elasticsearch-ruby, pull requests merged in 2020-10, with the labels that each got.

#1035 [DOCS] Reorganizes Overview and Installation chapters
  docs/client.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/overview.asciidoc
  docs/release_notes/78.asciidoc
  docs/release_notes/781.asciidoc
  docs/release_notes/index.asciidoc
Labels: 7.x, 8.0, documentation

#1039 [7.x][DOCS] Reorganizes Overview and Installation chapters
  docs/client.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/overview.asciidoc
  docs/release_notes/78.asciidoc
  docs/release_notes/781.asciidoc
  docs/release_notes/index.asciidoc
Labels: 7.x, backport, documentation

#1042 [CI] Removes 7.8 from Jenkins, adds 7.10
  .ci/jobs/elastic+elasticsearch-ruby+7.10.yml
Labels: CI

#1045 [CI] Catch and log errors when parsing YAML tests on test runner
  api-spec-testing/test_file.rb
Labels: 7.x, backport

#1046 [CI] Catch and log errors when parsing YAML tests on test runner
  api-spec-testing/test_file.rb
Labels: 7.10, backport

#1048 [XPACK] Adds security.clear_api_key_cache
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/security/clear_api_key_cache.rb
  elasticsearch-xpack/test/unit/security/clear_api_key_cache_test.rb
Labels: 7.10, 7.x, backport

#1050 [CI] Adds option to run a dir of tests in addition to a single test file in YAML test runner
  api-spec-testing/README.md
  elasticsearch-api/spec/rest_yaml_tests_helper.rb
  elasticsearch-xpack/spec/rest_yaml_tests_helper.rb
Labels: 7.x, backport, test-runner

#1049 [CI] Adds option to run a dir of tests in addition to a single test file in YAML test runner
  api-spec-testing/README.md
  elasticsearch-api/spec/rest_yaml_tests_helper.rb
  elasticsearch-xpack/spec/rest_yaml_tests_helper.rb
Labels: 7.x, 8.0, test-runner

#1056 [DOCS] Makes minor changes in section titles and fixes version numbers in Installation
  docs/installation.asciidoc
  docs/model.asciidoc
  docs/overview.asciidoc
  docs/persistence.asciidoc
  docs/rails.asciidoc
Labels: 7.x, 8.0, documentation

#1063 [API] Adds snapshot.clone endpoint
  elasticsearch-api/lib/elasticsearch/api/actions/snapshot/clone.rb
  elasticsearch-api/spec/elasticsearch/api/actions/snapshot/clone_spec.rb
Labels: 7.10, elasticsearch-api

#1057 Test Runner: expand_wildcards on xpack indices clean up
  api-spec-testing/test_file.rb
Labels: 7.x, 8.0, test-runner

#1066 Test Runner: expand_wildcards on xpack indices clean up
  api-spec-testing/test_file.rb
Labels: 7.x, test-runner
