Repository elastic/elasticsearch-ruby, pull requests merged in 2021-02, with the labels that each got.

#1181 [CI] Updates CI scripts
  .ci/functions/cleanup.sh
  .ci/functions/imports.sh
  .ci/functions/wait-for-container.sh
  .ci/jobs/defaults.yml
  .ci/run-elasticsearch.sh
  .ci/run-repository.sh
  .ci/run-tests
  .ci/test-matrix.yml
Labels: CI

#1183 [Tests] Updates tests for new license terms
  Rakefile
  api-spec-testing/test_file.rb
  elasticsearch-xpack/spec/rest_yaml_tests_helper.rb
Labels: CI, test-runner

#1184 Updates docker task to new license terms
  rake_tasks/docker_tasks.rake
Labels: CI

#1182 [DOCS] Adds Configuration section to Ruby book
  docs/advanced-config.asciidoc
  docs/basic-config.asciidoc
  docs/config.asciidoc
  docs/index.asciidoc
Labels: 7.x, 8.0, documentation

#1187 [7.x][DOCS] Adds Configuration section to Ruby book (#1182)
  docs/advanced-config.asciidoc
  docs/basic-config.asciidoc
  docs/config.asciidoc
  docs/index.asciidoc
Labels: 7.x, backport, documentation

#1189 Minor cleanup
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
Labels: 6.x

#1188 [CLIENT] When version is pre/alpha, use X.X.Xp for meta header version
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/meta_header_spec.rb
  elasticsearch/lib/elasticsearch.rb
Labels: 8.0, elasticsearch-transport

#1193 [CLIENT] When version is pre/alpha, use X.X.Xp for meta header version
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/meta_header_spec.rb
  elasticsearch/lib/elasticsearch.rb
Labels: 6.x, backport

#1194 [CLIENT] When version is pre/alpha, use X.X.Xp for meta header version
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/meta_header_spec.rb
  elasticsearch/lib/elasticsearch.rb
Labels: 6.x, backport

#1192 [CLIENT] When version is pre/alpha, use X.X.Xp for meta header version
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/meta_header_spec.rb
  elasticsearch/lib/elasticsearch.rb
Labels: backport

#1191 [CLIENT] When version is pre/alpha, use X.X.Xp for meta header version
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/spec/elasticsearch/transport/meta_header_spec.rb
  elasticsearch/lib/elasticsearch.rb
Labels: 7.x, backport

#1195 [CI] Skip specific component templates in cleanup
  api-spec-testing/test_file.rb
Labels: 7.x, CI

#1196 [CI] Skip specific component templates in cleanup
  api-spec-testing/test_file.rb
Labels: CI

#1197 [CI] Skip specific component templates in cleanup
  api-spec-testing/test_file.rb
Labels: 8.0, CI

#1190 [DOCS] Updates release notes for 7.11
  CHANGELOG.md
  docs/release_notes/711.asciidoc
  docs/release_notes/index.asciidoc
Labels: documentation

#1201 [DOCS] Updates release notes for 7.11
  CHANGELOG.md
  docs/release_notes/711.asciidoc
  docs/release_notes/index.asciidoc
Labels: documentation

#1202 [CI] Removes 7.10 Jenkins job
  .ci/jobs/elastic+elasticsearch-ruby+7.10.yml
Labels: CI

#1207 [DOCS] Updates release notes for 7.11.1
  CHANGELOG.md
  docs/release_notes/711.asciidoc
Labels: documentation

#1208 Test runner updates 7.x
  api-spec-testing/rspec_matchers.rb
Labels: CI, test-runner

#1212 [CI] Test Runner: Fix compare strings for empty in test runner
  api-spec-testing/rspec_matchers.rb
  elasticsearch-xpack/spec/xpack/rest_api_yaml_spec.rb
Labels: 8.0, backport, test-runner

#1214 [CI] Adds job for 7.12
  .ci/jobs/elastic+elasticsearch-ruby+7.12.yml
Labels: CI

#1213 Bump 7.x version
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch-transport/lib/elasticsearch/transport/version.rb
  elasticsearch-xpack/lib/elasticsearch/xpack/version.rb
  elasticsearch/elasticsearch.gemspec
  elasticsearch/lib/elasticsearch/version.rb
Labels: 7.x, CI

#1215 [DOCS] Warn about extensions being deprecated
  elasticsearch-extensions/README.md
Labels: 7.x, elasticsearch-extensions

#733 add auto_generate_synonyms_phrase_query
  elasticsearch-dsl/lib/elasticsearch/dsl/search/queries/query_string.rb
  elasticsearch-dsl/spec/elasticsearch/dsl/search/queries/query_string_spec.rb
Labels: elasticsearch-dsl

#1151 add minimum_should_match option to bool filters
  elasticsearch-dsl/lib/elasticsearch/dsl/search/filters/bool.rb
  elasticsearch-dsl/spec/elasticsearch/dsl/search/filters/bool_spec.rb
Labels: elasticsearch-dsl

#1216 [DSL] Removes auto_generate_phrase_queries deprecated parameter
  elasticsearch-dsl/lib/elasticsearch/dsl/search/queries/query_string.rb
  elasticsearch-dsl/spec/elasticsearch/dsl/search/queries/query_string_spec.rb
Labels: elasticsearch-dsl

#1044 Add support for calendar_interval to DateHistogram
  elasticsearch-dsl/lib/elasticsearch/dsl/search/aggregations/date_histogram.rb
  elasticsearch-dsl/spec/elasticsearch/dsl/search/aggregations/date_histogram_spec.rb
Labels: elasticsearch-dsl

#1217 [DSL] Removes deprecated interval parameter
  elasticsearch-dsl/lib/elasticsearch/dsl/search/aggregations/date_histogram.rb
  elasticsearch-dsl/spec/elasticsearch/dsl/search/aggregations/date_histogram_spec.rb
Labels: elasticsearch-dsl

#1218 [CI] Lock Stack version
  .ci/test-matrix.yml
  .github/workflows/7.x.yml
Labels: CI

#1220 [API] Generator: Find structure needs NDJSON input option
  elasticsearch-api/utils/thor/generator/endpoint_specifics.rb
  elasticsearch-api/utils/thor/templates/_perform_request.erb
  elasticsearch-xpack/lib/elasticsearch/xpack/api/actions/text_structure/find_structure.rb
Labels: 7.x, elasticsearch-api

#1223 [CI] Drops support for 2.5 in master since it is EOL 31/03
  .ci/test-matrix.yml
  .github/workflows/master.yml
Labels: 8.0, CI

#1226 Refactors Meta Header
  elasticsearch-transport/lib/elasticsearch/transport/client.rb
  elasticsearch-transport/lib/elasticsearch/transport/meta_header.rb
  elasticsearch-transport/spec/elasticsearch/transport/meta_header_spec.rb
Labels: 7.x, bug, elasticsearch-transport

#1229 [DOCS] Updates release notes for 7.11.2
  CHANGELOG.md
  docs/release_notes/711.asciidoc
Labels: 7.x, documentation

#1230 [DOCS] Updates release notes for 7.11.2
  CHANGELOG.md
  docs/release_notes/711.asciidoc
Labels: 8.0, documentation
