Repository elastic/elasticsearch-ruby, pull requests merged in 2023-07, with the labels that each got.

#2141 [DOCS] Adds getting started content based on the template
  docs/getting-started.asciidoc
  docs/images/es_endpoint.jpg
  docs/index.asciidoc
  docs/overview.asciidoc
Labels: documentation, 8.x

#2142 [DOCS] Adds getting started content based on the template (#2141)
  docs/getting-started.asciidoc
  docs/images/es_endpoint.jpg
  docs/index.asciidoc
  docs/overview.asciidoc
Labels: documentation, backport

#2143 [DOCS] Adds getting started content based on the template (#2141)
  docs/getting-started.asciidoc
  docs/images/es_endpoint.jpg
  docs/index.asciidoc
  docs/overview.asciidoc
Labels: documentation, backport

#2144 [DOCS] Updates the getting started button link on the landing page
  docs/index-custom-title-page.html
Labels: documentation

#2145 [DOCS] Updates the getting started button link on the landing page. #2144
  docs/index-custom-title-page.html
Labels: documentation, backport

#2148 [API] Test Runner: Updates PRESERVE_ILM_POLICY_IDS in wipe_cluster
  elasticsearch-api/api-spec-testing/wipe_cluster.rb
Labels: elasticsearch-api, test-runner

#2151 [API] Skips new ml 3rd party test
  elasticsearch-api/spec/rest_api/skipped_tests_platinum.yml
Labels: Skipped tests

#2153 [API] Test Runner: Adds elastic-connectors and search-acl-filter to platinum templates
  elasticsearch-api/api-spec-testing/wipe_cluster.rb
Labels: elasticsearch-api, 8.x

#2154 [DOCS] Restructures repo readme
  README.md
Labels: documentation

#2155 [8.9][DOCS] Restructures repo readme (#2154)
  README.md
Labels: documentation

#2156 [8.8][DOCS] Restructures repo readme (#2154)
  README.md
Labels: documentation

#2158 [API] Implements EQL async with missing events test manually
  elasticsearch-api/spec/platinum/integration/eql/eql_async_spec.rb
  elasticsearch-api/spec/platinum/integration/ml/get_memory_stats_spec.rb
  elasticsearch-api/spec/rest_api/skipped_tests_platinum.yml
Labels: elasticsearch-api, test-runner

#2159 Update README.md
  README.md
Labels: documentation, 7.17
