Repository elastic/elasticsearch-ruby, pull requests merged in 2023-11, with the labels that each got.

#2236 [API] Test Runner: Skips knn specific tests
  elasticsearch-api/spec/rest_api/skipped_tests_free.yml
Labels: test-runner

#2235 [DOCS] Updates Troubleshooting for adapters information
  docs/troubleshooting.asciidoc
Labels: documentation

#2241 [CI] Artifact task remove unnecessary build_hash
  rake_tasks/elasticsearch_tasks.rake
Labels: CI

#2246 [DOCS] Adds a signpost for downloading ES or signing-up for ESS
  README.md
Labels: documentation

#2247 Update build badges in README.md
  README.md
Labels: documentation
