Repository elastic/elasticsearch-ruby, pull requests merged in 2023-03, with the labels that each got.

#2025 Updates minitest-reporters to >= 1.6 and updates options
  elasticsearch-api/elasticsearch-api.gemspec
  elasticsearch-api/spec/unit_tests_platinum/test_helper.rb
Labels: test

#2030 [CI] Buildkite: Use annotate for test results
  .buildkite/log-results.sh
Labels: CI

#2032 [8.7] [CI] Buildkite: Use annotate for test results
  .buildkite/log-results.sh
Labels: backport, CI

#2035 [CI] Removes Jenkins jobs
  .ci/jobs/elastic+elasticsearch-ruby+7.17.yml
  .ci/jobs/elastic+elasticsearch-ruby+8.5.yml
  .ci/jobs/elastic+elasticsearch-ruby+8.6.yml
Labels: CI

#2034 Buildkite failed tests reformatting
  .buildkite/log-results.sh
Labels: CI

#2040 [8.7][DOCS] Creates custom title page for the Ruby client book
  docs/index-custom-title-page.html
Labels: documentation, backport

#2042 [main][backport] Fix typo `exaample` in `advanced-config.asciidoc`
  docs/advanced-config.asciidoc
Labels: backport, 8.x

#2039 [DOCS] Adds Release Notes for 8.7
  CHANGELOG.md
  docs/release_notes/87.asciidoc
  docs/release_notes/index.asciidoc
Labels: documentation

#2045 [8.7][DOCS] Adds Release Notes for 8.7
  CHANGELOG.md
  docs/release_notes/87.asciidoc
  docs/release_notes/index.asciidoc
Labels: documentation, backport

#2046 [DOCS] Adds logo to the landing page hero image and changes tagline
  docs/index-custom-title-page.html
Labels: documentation

#2047 [8.7][DOCS] Adds logo to the landing page hero image and changes tagline
  docs/index-custom-title-page.html
Labels: documentation, backport
