Repository elastic/elasticsearch-ruby, pull requests merged in 2024-02, with the labels that each got.

#2296 [API] Test runner: Migrates query user test to manual
  elasticsearch-api/spec/platinum/integration/security/users_query_spec.rb
  elasticsearch-api/spec/rest_api/skipped_tests_platinum.yml
Labels: test-runner

#2299 [8.12][Backport] Drop runtime dependency on base64
  elasticsearch-api/api-spec-testing/test_file/task_group.rb
  elasticsearch-api/spec/platinum/integration/api_key/api_key_invalidation_spec.rb
  elasticsearch/elasticsearch.gemspec
  elasticsearch/lib/elasticsearch.rb
  elasticsearch/spec/unit/api_key_spec.rb
Labels: backport, 8.x

#2307 [API] Migrates api_key_with_aggs test to manual integration
  elasticsearch-api/spec/platinum/integration/api_key/api_key_query_with_aggs_spec.rb
  elasticsearch-api/spec/rest_api/skipped_tests_platinum.yml
Labels: elasticsearch-api, Skipped tests

#2313 [DOCS] Reviews troubleshooting docs
  docs/troubleshooting.asciidoc
Labels: documentation, 8.x

#2315 [DOCS] Reviews troubleshooting docs.
  docs/troubleshooting.asciidoc
Labels: documentation, backport

#2317 [8.13][DOCS] Adds compatibility matrix to the Install section
  README.md
  docs/installation.asciidoc
Labels: documentation, backport

#2319 [CI] Passes STACK_VERSION to docker run
  .buildkite/run-client.sh
Labels: CI

#2318 [8.12][DOCS] Adds compatibility matrix to the Install section
  README.md
  docs/installation.asciidoc
Labels: documentation, backport

#2320 [CI] Passes STACK_VERSION to docker run
  .buildkite/run-client.sh
Labels: backport, CI

#2322 [API] Test Runner: Skips ml/3rd_party_deployment test
  elasticsearch-api/spec/rest_api/skipped_tests_platinum.yml
Labels: test-runner
