Repository elastic/elasticsearch-ruby, pull requests merged in 2025-03, with the labels that each got.

#2589 [CI] Updates STACK_VERSION to 8.17.2-SNAPSHOT
  .buildkite/pipeline.yml
  .github/workflows/8.17.yml
  .github/workflows/otel.yml
Labels: CI, 8.x

#2590 [API] Updates esql.async_query_stop
  elasticsearch-api/lib/elasticsearch/api/actions/esql/async_query_stop.rb
Labels: elasticsearch-api, 9.x

#2592 [CI] Updates transport version
  .buildkite/pipeline.yml
Labels: CI, 9.x

#2593 [CI] Updates transport version
  .buildkite/pipeline.yml
Labels: CI, 8.x

#2595 [docs] Fix external links
  docs/reference/connecting.md
  docs/reference/dsl.md
  docs/reference/transport.md
Labels: documentation

#2597 [DOCS] Delete preview action for old Asciidoc system
  .github/workflows/docs-preview.yml
Labels: documentation

#2604 [docs] Miscellaneous docs clean up
  docs/docset.yml
  docs/reference/connecting.md
  docs/reference/getting-started.md
  docs/reference/images/api_key_name.png
  docs/reference/images/cloud_api_key.png
  docs/reference/images/cloud_id.png
  docs/reference/images/create_api_key.png
  docs/reference/images/es_endpoint.jpg
  docs/reference/images/otel-waterfall-retry.png
  docs/reference/images/otel-waterfall-with-http.png
  docs/reference/images/otel-waterfall-without-http.png
  docs/reference/opentelemetry.md
Labels: documentation

#2605 Updates navigation titles and descriptions for release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: documentation

#2610 [Gem] Don't use Rubocop with JRuby
  Gemfile
  elasticsearch-api/utils/Gemfile
Labels: CI, 9.x
