Repository elastic/elasticsearch-ruby, pull requests merged in 2025-04, with the labels that each got.

#2609 Fix mapped_pages front matter on docs/reference/index
  docs/reference/index.md
Labels: bug

#2614 [CI] Updates GitHub Actions for 9.0
  .github/workflows/9.0.yml
Labels: CI, 9.x

#2617 [Backport][8.16][Gem] Don't use Rubocop with JRuby
  Gemfile
  elasticsearch-api/utils/Gemfile
Labels: backport, CI, 8.x

#2622 [DOCS] Updates release notes for 8.17
  CHANGELOG.md
  docs/release_notes/817.asciidoc
Labels: documentation, 8.x

#2623 [DOCS] Updates release notes for 8.17
  CHANGELOG.md
  docs/release_notes/817.asciidoc
Labels: documentation, 8.x

#2624 [9.0][API] Removes inference EIS endpoints
  elasticsearch-api/lib/elasticsearch/api/actions/inference/post_eis_chat_completion.rb
  elasticsearch-api/lib/elasticsearch/api/actions/inference/put_eis.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch-api/spec/unit/actions/inference/post_eis_chat_completion_spec.rb
  elasticsearch-api/spec/unit/actions/inference/put_eis_spec.rb
Labels: elasticsearch-api, 9.x

#2626 [9.0][API] Removes timeout from snapshot.clone endpoint
  elasticsearch-api/lib/elasticsearch/api/actions/snapshot/clone.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
Labels: elasticsearch-api, 9.x

#2627 [API] Removes timeout from snapshot.clone endpoint
  elasticsearch-api/lib/elasticsearch/api/actions/snapshot/clone.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
Labels: elasticsearch-api, 9.x

#2628 [Docs] Restore troubleshooting content
  docs/reference/toc.yml
  docs/reference/troubleshoot.md
Labels: documentation, backport, 9.x

#2629 [docs] Update APM, Synthetics, Uptime links
  docs/reference/opentelemetry.md
Labels: documentation

#2639 [9.0][API] Removes knn_search
  elasticsearch-api/lib/elasticsearch/api/actions/knn_search.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch-api/spec/unit/actions/knn_search_spec.rb
  elasticsearch-api/spec/unit/perform_request_spec.rb
Labels: elasticsearch-api, 9.x

#2642 [CI] Updates otel GitHub Action and Buildkite yaml test branch for 8.18
  .buildkite/pipeline.yml
  .github/workflows/otel.yml
Labels: CI, 8.x

#2643 [DOCS] Release notes 8.18
  CHANGELOG.md
  docs/release_notes/818.asciidoc
  docs/release_notes/index.asciidoc
Labels: documentation, 8.x

#2646 [CI] Updates version in pipeline
  .buildkite/pipeline.yml
Labels: CI, 9.x

#2644 Bumps version to 8.18.0
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch/elasticsearch.gemspec
  elasticsearch/lib/elasticsearch/version.rb
Labels: 8.x

#2645 Bumps version to 8.18.0
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch/elasticsearch.gemspec
  elasticsearch/lib/elasticsearch/version.rb
Labels: 8.x

#2647 [DOCS] Update README.md - compatibility
  README.md
Labels: documentation

#2648 [DOCS] Updates CHANGELOG
  CHANGELOG.md
Labels: documentation, 9.x

#2649 [DOCS] Update README.md - compatibility
  README.md
Labels: documentation, 9.x

#2650 [DOCS] Updates build badges on README.md
  README.md
Labels: documentation

#2652 [Tests] Removes skipped tests in YAML runner
  elasticsearch-api/spec/yaml-test-runner/run.rb
Labels: test-runner, 9.x

#2653 [9.0][Tests] Removes skipped tests in YAML runner
  elasticsearch-api/spec/yaml-test-runner/run.rb
Labels: test-runner, 9.x

#2655 [API] Adds esql get_query and list_queries
  elasticsearch-api/lib/elasticsearch/api/actions/esql/get_query.rb
  elasticsearch-api/lib/elasticsearch/api/actions/esql/list_queries.rb
  elasticsearch-api/spec/unit/actions/esql/get_query_spec.rb
  elasticsearch-api/spec/unit/actions/esql/list_queries_spec.rb
Labels: elasticsearch-api, 9.x

#2659 Updates API generated code, headers
  elasticsearch-api/lib/elasticsearch/api/actions/bulk.rb
  elasticsearch-api/lib/elasticsearch/api/actions/fleet/msearch.rb
  elasticsearch-api/lib/elasticsearch/api/actions/msearch.rb
  elasticsearch-api/lib/elasticsearch/api/actions/msearch_template.rb
  elasticsearch-api/lib/elasticsearch/api/actions/text_structure/find_structure.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
  elasticsearch-api/spec/unit/actions/bulk_spec.rb
  elasticsearch-api/spec/unit/actions/fleet/msearch_spec.rb
  elasticsearch-api/spec/unit/actions/msearch_spec.rb
  elasticsearch-api/spec/unit/actions/msearch_template_spec.rb
  elasticsearch-api/spec/unit/actions/text_structure/find_structure_spec.rb
  elasticsearch/lib/elasticsearch.rb
Labels: elasticsearch-api, elasticsearch-gem, 9.x

#2663 [DOCS] Release notes 9.0.1 and 9.0.2
  CHANGELOG.md
  docs/release-notes/breaking-changes.md
  docs/release-notes/index.md
Labels: documentation, 9.x

#2667 [Gem] Updates setting content-type, accept to not overwrite user set …
  elasticsearch/lib/elasticsearch.rb
  elasticsearch/spec/unit/headers_spec.rb
Labels: elasticsearch-gem, 9.x

#2668 [API] Updates synonyms.delete_synonym_rule, synonyms.put_synonym, synonyms.put_synonym_rule
  elasticsearch-api/lib/elasticsearch/api/actions/machine_learning/get_data_frame_analytics_stats.rb
  elasticsearch-api/lib/elasticsearch/api/actions/machine_learning/get_datafeed_stats.rb
  elasticsearch-api/lib/elasticsearch/api/actions/machine_learning/get_job_stats.rb
  elasticsearch-api/lib/elasticsearch/api/actions/synonyms/delete_synonym_rule.rb
  elasticsearch-api/lib/elasticsearch/api/actions/synonyms/put_synonym.rb
  elasticsearch-api/lib/elasticsearch/api/actions/synonyms/put_synonym_rule.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
Labels: elasticsearch-api, 9.x

#2669 [API] Updates source code docs
  elasticsearch-api/lib/elasticsearch/api/actions/machine_learning/get_data_frame_analytics_stats.rb
  elasticsearch-api/lib/elasticsearch/api/actions/machine_learning/get_datafeed_stats.rb
  elasticsearch-api/lib/elasticsearch/api/actions/machine_learning/get_job_stats.rb
  elasticsearch-api/lib/elasticsearch/api/version.rb
Labels: elasticsearch-api, 9.x

#2671 [DOCS] Updates CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation, backport, 9.x
